[build]
command = "npm run build"
output_directory = ".next"

[vars]
ENVIRONMENT = "production"
APP_VERSION = "1.0.0"

[[d1_databases]]
binding = "DB"
database_name = "nitchie-app-builder-db"
database_id = "ed555740-5d8e-479f-82c7-a4cdd44f8e04" # Replace with the Database ID from wrangler d1 create command

[pages]
project_name = "nitchie-app-builder"
production_branch = "master"
compatibility_flags = ["nodejs_compat"]

[build.environment]
NODE_VERSION = "20"
NPM_VERSION = "10"

[dev]
port = 3000
local_protocol = "https"
